
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 24 15:32:08 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 47;
  public static final int CONST = 6;
  public static final int GRTEQ = 41;
  public static final int GRT = 40;
  public static final int LPAREN = 23;
  public static final int SEMI = 21;
  public static final int CONTINUE = 15;
  public static final int LSS = 42;
  public static final int MINUS = 29;
  public static final int RPAREN = 24;
  public static final int LSSEQ = 43;
  public static final int AND = 37;
  public static final int OR = 36;
  public static final int BOOL = 46;
  public static final int COMMA = 22;
  public static final int CLASS = 4;
  public static final int INC = 34;
  public static final int DIV = 31;
  public static final int PLUS = 19;
  public static final int ASSIGN = 20;
  public static final int IF = 7;
  public static final int LSQBRACE = 27;
  public static final int DOT = 18;
  public static final int FINDANY = 17;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 38;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int NUMBER = 44;
  public static final int MOD = 32;
  public static final int IDENT = 45;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int ARROW = 33;
  public static final int FOREACH = 16;
  public static final int LBRACE = 25;
  public static final int ELSE = 5;
  public static final int READ = 11;
  public static final int WHILE = 8;
  public static final int RBRACE = 26;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int DIFF = 39;
  public static final int RSQBRACE = 28;
  public static final int DEC = 35;
  public static final int PRINT = 10;
}

